# Generated by Django 5.0.1 on 2025-09-12 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_number', models.CharField(help_text='Bill of Lading Number - unique identifier for the shipment', max_length=50, unique=True, verbose_name='BL Number')),
                ('container_no', models.CharField(db_index=True, help_text='Container identification number', max_length=50, verbose_name='Container Number')),
                ('chassis_no', models.CharField(blank=True, db_index=True, help_text='Chassis number for tracking', max_length=50, null=True, verbose_name='Chassis Number')),
                ('shipping_line', models.CharField(help_text='Name of the shipping company', max_length=100, verbose_name='Shipping Line')),
                ('consignee', models.CharField(help_text='Recipient of the shipment', max_length=200, verbose_name='Consignee')),
                ('shipper', models.CharField(help_text='Sender of the shipment', max_length=200, verbose_name='Shipper')),
                ('eta', models.DateField(help_text='Expected arrival date at destination', verbose_name='ETA (Expected Time of Arrival)')),
                ('gate_out_date', models.DateField(blank=True, help_text='Date when container left the port/facility', null=True, verbose_name='Gate Out Date')),
                ('free_days', models.IntegerField(default=0, help_text='Number of free storage days at port', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Free Days')),
                ('demurrage_days', models.IntegerField(default=0, help_text='Number of days exceeding free period', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Demurrage Days')),
                ('duty_status', models.BooleanField(default=False, help_text='Check if duty has been paid', verbose_name='Duty Status')),
                ('penalty_duty', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount of penalty duty charges', max_digits=12, verbose_name='Penalty Duty Amount')),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional charges incurred at the port', max_digits=12, verbose_name='Extra Charges at Port')),
                ('freight_payment', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid for freight services', max_digits=12, verbose_name='Freight Payment Amount')),
                ('freight_status', models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid'), ('pending', 'Pending')], default='pending', help_text='Current status of freight payment', max_length=20, verbose_name='Freight Payment Status')),
                ('towing_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost for towing services', max_digits=10, verbose_name='Towing Charge')),
                ('towing_destination', models.CharField(blank=True, help_text='Final destination for towing', max_length=200, verbose_name='Towing Destination')),
                ('towing_car_owner', models.CharField(blank=True, help_text='Owner of the towing vehicle', max_length=200, verbose_name='Towing Car Owner')),
                ('towing_status', models.BooleanField(default=False, help_text='Check if towing charges have been paid', verbose_name='Towing Payment Status')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the shipment contents', verbose_name='Cargo Description')),
                ('item_quantity', models.IntegerField(default=1, help_text='Number of items in the shipment', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Item Quantity')),
                ('agent_assigned', models.CharField(blank=True, help_text='Agent responsible for handling this shipment', max_length=100, verbose_name='Assigned Agent')),
                ('supervisor_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Current supervisor review status', max_length=20, verbose_name='Supervisor Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bl_number'], name='shipments_s_bl_numb_542848_idx'), models.Index(fields=['container_no'], name='shipments_s_contain_13bdce_idx'), models.Index(fields=['chassis_no'], name='shipments_s_chassis_55aacb_idx'), models.Index(fields=['shipping_line'], name='shipments_s_shippin_a70054_idx'), models.Index(fields=['agent_assigned'], name='shipments_s_agent_a_c25ead_idx'), models.Index(fields=['eta'], name='shipments_s_eta_ed8864_idx')],
            },
        ),
    ]
